### ISSUE TITLE
Input optimization plan

### ISSUE THREAD

**Issue by cptbtptpbcptdtptp** [galacean/engine#1332]
- [x]  Fix firefox adapter bug #1002 
- [x]  Support inputManager disable function #1331 
- [x]  Support replace listening element （ canvas -> document ） @JujieX 
- [x]  Cancel `focusOn` and `tabIndex`
- [x]  Support enable or disable `preventDefault`
- [x]  Can get hitResult in `Pointer` @luzhuang
- [x]  #1355 Replace the `inputmanager.frameCount` with `engine.time.frameCount` @GuoLei1990 
- [x]  Can get key click record in `Pointer` 
- [x]  https://github.com/ant-galaxy/oasis-engine/pull/1359 Improve input scalability

At the same time, it is necessary to adapt
- [ ]  OrbitControl
- [ ]  FreeControl
- [ ] ……
