### ISSUE TITLE
Iteration Plan Focus for 1.1 milestone

### ISSUE THREAD

**Issue by GuoLei1990** [galacean/engine#1549]
### Plan Items

| Mark | Description                                       |
| ---- | ------------------------------------------------- |
| 🏃🎨   | work in progress, **design** phase                |
| 🏃🧑🏻‍💻 | work in progress, **development** phase           |
| 🏃🕵🏻  | work in progress, **CR** phase                    |
| ✋    | blocked task                                      |
| 💪    | stretch goal for this iteration                   |
| 🔴    | missing issue reference                           |
| 🔵    | more investigation required to remove uncertainty |
| ⚫    | under discussion within the team                  |
| ⬛    | a large work item, larger than one iteration      |

### Enhancement 

**Material**

- [x] https://github.com/galacean/engine/issues/1351 @zhuxudong 
- [ ] ~~https://github.com/galacean/engine/issues/935~~ @zhuxudong 

**Scene**

- [x] https://github.com/galacean/engine/issues/1537 @GuoLei1990 

**Shader**

- [x] https://github.com/galacean/engine/issues/191 @Sway007 

**Input**

- [ ] https://github.com/galacean/engine/issues/1196 @cptbtptpbcptdtptp 

**Resource**

- [x] https://github.com/galacean/engine/issues/1211 @gz65555 
- [x] https://github.com/galacean/engine/issues/839 @gz65555 
- [ ] https://github.com/galacean/engine/issues/1551 @zhuxudong 

**Physics**

- [ ] ~~https://github.com/galacean/engine/issues/1349~~ @yangfengzzz 
- [ ] ~~https://github.com/galacean/engine/issues/1554~~ @yangfengzzz 
- [ ] ~~https://github.com/galacean/engine/issues/1271~~ @yangfengzzz 

**Animation**

- [ ] ~~https://github.com/galacean/engine/issues/1236~~ @luzhuang 
- [ ] ~~https://github.com/galacean/engine/issues/208~~ @luzhuang 
- [ ] ~~https://github.com/galacean/engine/issues/792~~ @luzhuang 
- [ ] ~~https://github.com/galacean/engine/issues/1356~~ @luzhuang  

**Mesh**

- [x] https://github.com/galacean/engine/issues/1265 @GuoLei1990 
- [x] https://github.com/galacean/engine/issues/1438 @GuoLei1990 

**Effect**

- [x] https://github.com/galacean/engine/issues/1346 @GuoLei1990 

**Audio**

- [ ] https://github.com/galacean/engine/issues/643 @JujieX 

**Pipeline**

- [ ] https://github.com/galacean/engine/issues/1553 @cptbtptpbcptdtptp @singlecoder 
- [x] https://github.com/galacean/engine/issues/1550 @GuoLei1990 

**XR**

- [ ] https://github.com/galacean/engine/issues/1348 @cptbtptpbcptdtptp 

**Video**

- [x] https://github.com/galacean/engine/issues/1368 @singlecoder 

**GUI**

- [ ] ~~https://github.com/galacean/engine/issues/649~~ @singlecoder 

**Test**

- [ ] e2e test framework @luzhuang 

### Other issues and details

-  https://github.com/ant-galaxy/oasis-engine/milestone/10
